import Head from 'next/head'
//import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Burger Queen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1><a href='/prueba'> Ir a prueba componente</a> </h1>
          <h1> <a href='/nav'> Ir a Prueba Header </a> </h1>
          <h1> <a href='/menuvistas'> Ir a Prueba Menu vistas </a> </h1>
        </div>

      </main>
    </>
  )
}
