import Head from 'next/head'
//import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Burger Queen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1><Link href="/vistameseros" > Ir a Menu vista mesero</Link> </h1>
        </div>

      </main>
      <footer> 
      <p>Copyright © 2023 Natalia Aspee & Nelly Cumpa</p>
      <p> A Project Built with Next.js </p> </footer>
    </>
  )
}
