import prueba from '../styles/prueba.module.css'
import Link from 'next/link'


export default function Prueba() {
  return (
    <div>
      <title>Burger Queen</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />

      <main >
        <div>
          <header>
            <h1 className={prueba.title}>Es una prueba xoxo</h1>
          </header>
          <p>prueba componente </p>
          <h1><Link href="/" > Ir al Home </Link> </h1>
        </div>

      </main>
    </div>
  )
}
